version: "3"
services:
  test:
    build: .
    container_name: rw-metadata-test
    environment:
      CT_REGISTER_MODE: auto
      NODE_ENV: test
      PORT: 5005
      API_VERSION: v1
      LOCAL_URL: http://127.0.0.1:5005
      CT_URL: http://127.0.0.1:9000
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      MONGO_PORT_27017_TCP_ADDR: mongo
      FASTLY_ENABLED: "false"
    command: test
    depends_on:
      - mongo

  mongo:
    image: mongo:3.4
    command: --smallfiles
    ports:
      - "27017"
