version: "3"
services:
  develop:
    build: .
    container_name: rw-metadata-develop
    ports:
      - "4000:4000"
    env_file:
      - dev.env
    environment:
      PORT: 4000
      NODE_PATH: app/src
      CT_REGISTER_MODE: auto
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      API_VERSION: v1
      MONGO_PORT_27017_TCP_ADDR: mongo
      LOCAL_URL: http://mymachine:4000
      FASTLY_ENABLED: "false"
    command: develop
    depends_on:
      - mongo
    volumes:
      - ./app:/opt/rw-metadata/app

  mongo:
    image: mongo:3.4
    container_name: rw-metadata-mongo-develop
    command: --smallfiles
    ports:
      - "27017"
    volumes:
      # in osx the host machine volume directory cannot be under /Users
      # http://stackoverflow.hex1.ru/questions/34390220/how-to-mount-external-volume-for-mongodb-using-docker-compose-and-docker-machine
      - $HOME/docker/data/rw-metadata:/data/db
    restart: always
