apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: metadata
    app: rw
  name: metadata
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: metadata
    spec:
      containers:
      - name: metadata
        image: vizzuality/metadata
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.5"
            memory: "256M"
          limits:
            cpu: "1"
            memory: "512M"
        args:
          - start
        env:
          - name: PORT
            value: "4000"
          - name: NODE_ENV
            value: prod
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://metadata.default.svc.cluster.local:4000
          - name: MONGO_URI
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: METADATA_MONGO_URI
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION

        ports:
          - containerPort: 4000
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthcheck
            port: 4000
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /healthcheck
            port: 4000
          failureThreshold: 3
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15

      restartPolicy: Always
